name : AI Research Assistant

on:
  push:
    branches : [ main ]
  pull_request:
    branches : [ main ]


jobs:
  build:
    runs-on:ubuntu-latest.

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name : Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


      - name: Run tests
        run: |
          pip install pytest
          pytest !! echho "No tests found! - Skipping"